"""removing unique constraint from cnr

Revision ID: 27c49e88d0f9
Revises: cd65c1494116
Create Date: 2026-02-25 15:54:37.187540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27c49e88d0f9'
down_revision: Union[str, None] = 'cd65c1494116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cases_cino', table_name='cases')

    op.create_index(
        'uq_cases_workspace_cino',
        'cases',
        ['workspace_id', 'cino'],
        unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_cases_workspace_cino', table_name='cases')
    op.create_index(op.f('ix_cases_cino'), 'cases', ['cino'], unique=True)
    # ### end Alembic commands ###
