"""add workspace refresh job

Revision ID: 3ebdb1b3b925
Revises: dfc6a162a067
Create Date: 2026-02-14 21:48:16.754573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebdb1b3b925'
down_revision: Union[str, None] = 'dfc6a162a067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
