"""add_cases

Revision ID: 633b6b13d031
Revises: 705bc4b75b2f
Create Date: 2026-02-04 02:21:06.686926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633b6b13d031'
down_revision: Union[str, None] = '705bc4b75b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('cino', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('internal_status', sa.String(), nullable=False),
    sa.Column('court_name', sa.String(), nullable=True),
    sa.Column('court_level', sa.String(), nullable=True),
    sa.Column('court_bench', sa.String(), nullable=True),
    sa.Column('court_code', sa.String(), nullable=True),
    sa.Column('summary_petitioner', sa.String(), nullable=True),
    sa.Column('summary_respondent', sa.String(), nullable=True),
    sa.Column('summary_short_title', sa.String(), nullable=True),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('filing_number', sa.String(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('first_hearing_date', sa.Date(), nullable=True),
    sa.Column('next_hearing_date', sa.Date(), nullable=True),
    sa.Column('last_hearing_date', sa.Date(), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('case_stage', sa.String(), nullable=True),
    sa.Column('case_status_text', sa.String(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('sync_last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('sync_error_message', sa.Text(), nullable=True),
    sa.Column('meta_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('meta_source', sa.String(), nullable=True),
    sa.Column('meta_source_url', sa.String(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_cino'), 'cases', ['cino'], unique=True)
    op.create_index(op.f('ix_cases_workspace_id'), 'cases', ['workspace_id'], unique=False)
    op.create_table('case_acts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('act_name', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('act_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_acts_case_id'), 'case_acts', ['case_id'], unique=False)
    op.create_table('case_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('hearing_date', sa.Date(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('judge', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_history_case_id'), 'case_history', ['case_id'], unique=False)
    op.create_table('case_parties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('is_petitioner', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('advocate', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_parties_case_id'), 'case_parties', ['case_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'cases', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_case_parties_case_id'), table_name='case_parties')
    op.drop_table('case_parties')
    op.drop_index(op.f('ix_case_history_case_id'), table_name='case_history')
    op.drop_table('case_history')
    op.drop_index(op.f('ix_case_acts_case_id'), table_name='case_acts')
    op.drop_table('case_acts')
    op.drop_index(op.f('ix_cases_workspace_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_cino'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
