"""change date to order_date in case_orders

Revision ID: a3994f7a6059
Revises: f5e728776e62
Create Date: 2026-02-23 21:49:19.505065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3994f7a6059'
down_revision: Union[str, None] = 'f5e728776e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_orders', sa.Column('order_date', sa.Date(), nullable=True))
    op.drop_column('case_orders', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_orders', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('case_orders', 'order_date')
    # ### end Alembic commands ###
