"""add file size & fix details in orders

Revision ID: ad3958bb385b
Revises: a3994f7a6059
Create Date: 2026-02-25 01:23:15.218518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad3958bb385b'
down_revision: Union[str, None] = 'a3994f7a6059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_orders', sa.Column('file_size', sa.Integer(), nullable=True))
    op.drop_column('case_orders', 'details')
    op.add_column('case_orders', sa.Column('order_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_orders', 'file_size')
    op.drop_column('case_orders', 'order_details')
    op.add_column('case_orders', sa.Column('details', sa.Text(), nullable=True))
    # ### end Alembic commands ###
