"""add multi-save-jobs

Revision ID: cd65c1494116
Revises: ad3958bb385b
Create Date: 2026-02-25 04:15:02.839260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd65c1494116'
down_revision: Union[str, None] = 'ad3958bb385b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_multi_save_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('total_cases', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_cases', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_cases', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_multi_save_jobs_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_multi_save_jobs')
    # ### end Alembic commands ###
