"""Add nature_of_disposal to cases

Revision ID: dfc6a162a067
Revises: 633b6b13d031
Create Date: 2026-02-11 20:29:33.759358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc6a162a067'
down_revision: Union[str, None] = '633b6b13d031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('pdf_filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_orders_case_id'), 'case_orders', ['case_id'], unique=False)
    op.add_column('cases', sa.Column('nature_of_disposal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'nature_of_disposal')
    op.drop_index(op.f('ix_case_orders_case_id'), table_name='case_orders')
    op.drop_table('case_orders')
    # ### end Alembic commands ###
