"""add file_path to case_orders

Revision ID: f5e728776e62
Revises: 26cca3206ff3
Create Date: 2026-02-23 21:20:30.313358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5e728776e62'
down_revision: Union[str, None] = '26cca3206ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_orders', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_orders', 'file_path')
    # ### end Alembic commands ###
